## Problem 1
#(a)
library(faraway)
data(gala)
lm<-lm(Endemics~Area+ Elevation+ Nearest + Scruz + Adjacent,gala)
summary(lm)
conf <- confint(lm)
conf
#(b)
lm1<-lm(Endemics~Area+ Elevation+ Adjacent,gala)
anova(lm1,lm)
install.packages("ellipse")
require("ellipse")
plot(ellipse(lm,c(4,5)),type = "l")
points(coef(lm)[4],coef(lm)[5],pch=19)
abline(v=confint(lm)[4,],lty=2)
abline(h=confint(lm)[5,],lty=2)
points(0,0,pch=19)
#(c)
pt(7.725, df=24)
1-pt(7.725, df=24)


## Problem 2
#(a)
data(sat)
help("sat")
lmprom2<-lm(total~takers+ratio+salary,sat)
summary(lmprom2)
#(c)
pt(-2.187,df=46)
#(e)
lmprom2e<-lm(total~takers+ratio+salary+expend,sat)
summary(lmprom2e)
xx<-lm(expend~salary,sat)
summary(xx)
xxx<-lm(expend~ratio,sat)
summary(xxx)
#(f)
lmprom2f<-lm(total~expend,sat)
summary(lmprom2f)
anova(lmprom2f,lmprom2e)
