#(1)
library(faraway)
data(teengamb)
teengamb$sex<-factor(teengamb$sex)
levels(teengamb$sex) <- c("male","female")
summary(teengamb)

lmorg<-lm(gamble~sex+income+status+verbal,teengamb)
summary(lmorg)
lmorgre<-lm(lmorg$residuals~lmorg$fitted.values)
summary(lmorgre)
par(mfrow=c(2,2))
plot(lmorg)

y=log(teengamb$gamble+1)
lmlog<-lm(y~teengamb$sex+teengamb$income+teengamb$status+teengamb$verbal)
summary(lmlog)
par(mfrow=c(2,2))
plot(lmlog)
lmlogre<-lm(lmlog$residuals~lmlog$fitted.values)
summary(lmlogre)

#(2)
#(a)
shapiro.test(lmlog$residual)

#(b)
ti <- rstudent(lmlog)
2*(1-pt(max(abs(ti)), df=42))

#(c)
cook <- cooks.distance(lmlog)
halfnorm(cook, nlab = 3, ylab="Cook’s distance")
result.max <- lm(y ~ sex + income+ status + verbal, data=teengamb,subset=(cook < max(cook)))
summary(result.max)
