#1
library(faraway) 
data(aatemp) 
#(a)
lm<-lm(temp~year,aatemp)
summary(lm)
plot(temp~year,aatemp)
abline(coefficients(lm))
par(mfrow=c(2,2))
plot(lm)
#(b)
require(nlme)
glmod <- gls(temp~year, correlation=corAR1 (form=~year), data=aatemp)
summary(glmod)
intervals(glmod,which="var-cov")
summary(glmod)$adj.r.squared
#(c)
lmpl10<-lm(temp~poly(year,10),data=aatemp)
summary(lmpl10)
lmpl5<-lm(temp~poly(year,5),data=aatemp)
summary(lmpl5)
plot(temp~year,aatemp)
points(aatemp$year, fitted(lmpl5),col="orange", pch=20)
predict(lmpl5,newdata = data.frame(year= 2020))
#(d)
mean(aatemp$temp,subset(aatemp$year<=1930))
plot(temp~year,aatemp,xlab="Year",ylab="Temp", main="temp in ann arbor michigan")
abline(v=1930, lty=5)
lhs<-function(x)ifelse(x<=1930, 47.74,0)
rhs<-function(x)ifelse(x>1930, x-1930,0)
gmod<-lm(temp~lhs(year)+rhs(year),aatemp)
x<-seq(1854,2000,by=1)
py<-gmod$coef[1]+gmod$coef[2]*lhs(x)+gmod$coef[3]*rhs(x)
lines(x,py)
summary(gmod)
g1<-lm(temp~I(47.74), aatemp,subset=(year<=1930))
g2<-lm(temp~year, aatemp, subset=(year>1930))
#(e)
library(splines)
knots<-c(1854,1854,1854,1854,1902,1951,2000,2000,2000, 2000)
byear<-splineDesign(knots,aatemp$year)
lmodb<-lm(temp~byear,aatemp)
matplot(aatemp$year, byear, type="l", col=1)
matplot(aatemp$year, cbind(aatemp$temp,lmodb$fit), type="pl", ylab="year", pch=20,lty=1,col=1)
summary(lmodb)
install.packages("AICcmodavg")
library(AICcmodavg)
models <- list(lm,lmpl5,gmod,lmodb)
mod.names <- c('modela', 'modelc','modeld','modele')
aictab(models, mod.names)

#2
library(MASS)
data(ozone)
q2lm<-lm(O3~temp+humidity+ibh,ozone)
bc<-boxcox(q2lm,plotit=T)
bc2<-boxcox(q2lm,plotit=T,lambda=seq(0.1, 0.5, by=0.1))
bc2$x[which(bc2$y==max(bc2$y))]
