#1
install.packages("leaps")
library(leaps)
library(faraway)
data(prostate)
#(a)
g <- lm (lpsa ~ . , data=prostate)
summary(g)
g <- update (g,.~. - gleason)
summary(g)
g <- update (g,.~. - lcp)
summary(g)
g <- update (g,.~. - pgg45)
summary(g)
g <- update (g,.~. - age)
summary(g)
g <- update (g,.~. - lbph)
summary(g)
#(b)
g <- lm (lpsa ~ . , data=prostate)
step(g)
#(c)
b<-regsubsets(lpsa~.,data=prostate)
summary(b)
rs<-summary(b)
plot (2:9, rs$adjr2, xlab="No. of Parameters",ylab="Adjusted R-squqre")
which.max(rs$adjr2)
#(d)
plot(2:9, rs$cp, xlab="No. of Parameters",ylab="Cp Statistic")
which.min(rs$cp)
d<-lm(lpsa~lcavol+ lweight+ svi+ lbph,data=prostate)
summary(d)
#2
data(trees)
df <- trees
n <-nrow(df)
lm.fit <- lm(log(Volume)  ~ polym(Girth,Height,degree=2) , data=trees)
summary(lm.fit)
regsubsets.out <- regsubsets(log(Volume)  ~ polym(Girth,Height,degree=2),data=trees) 
rs <- summary(regsubsets.out)
summary(regsubsets.out)
plot (2:6, rs$adjr2, xlab="No. of Parameters",ylab="Adjusted R-squqre")
plot (2:6, rs$cp, xlab="No. of Parameters",ylab="Cp Statistic")
lmn<-lm(log(Volume)~Girth+I(Girth^2)+Height,data=trees)
summary(lmn)
